#include "export/PdfExporter.hpp"

#include "Version.hpp"
#include "core/Error.hpp"
#include "core/Log.hpp"
#include "export/Process.hpp"

#include <format>
#include <fstream>

namespace docscan {

namespace {

// \page{page width}{page height}{x}{y}{image width}{image height}{file}, all sizes in points.
// \shipout puts the box's top-left corner at (1in + \hoffset, 1in + \voffset), the page's top-left corner.
constexpr std::string_view kPreamble = R"(% Generated by docscan {0}
\pdfminorversion=5 \pdfcompresslevel=9 \pdfobjcompresslevel=2
\pdfinfo{{/Creator (docscan {0})}}
\hoffset=-1truein \voffset=-1truein
\def\page#1#2#3#4#5#6#7{{\pdfpagewidth=#1bp \pdfpageheight=#2bp
  \shipout\vbox{{\kern#4bp\hbox{{\kern#3bp\pdfximage width #5bp height #6bp {{#7}}\pdfrefximage\pdflastximage}}}}}}
)";

} // namespace

PdfExporter::PdfExporter(std::filesystem::path output, PaperSize paper, int quality)
    : output_(std::move(output)), paper_(paper), encoder_(quality)
{
}

void PdfExporter::begin(std::size_t pageCount)
{
    const auto pdftex = Process::find("pdftex");
    if (!pdftex)
        throw ProcessingError("pdftex not found; install it with: pacman -S texlive-basic");
    pdftex_ = *pdftex;
    workDir_.emplace();
    pages_.assign(pageCount, {});
}

void PdfExporter::addPage(std::size_t index, const cv::Mat& page)
{
    const auto file = encoder_.write(page, workDir_->path() / std::format("page-{:04}", index + 1));
    pages_[index] = {file.filename(), page.size()};
}

void PdfExporter::finish()
{
    const auto dir = workDir_->path();
    std::ofstream(dir / "document.tex") << texDocument();

    const int status = Process::run(pdftex_, {"-interaction=batchmode", "-halt-on-error", "document.tex"}, dir);
    const auto pdf = dir / "document.pdf";
    if (status != 0 || !std::filesystem::exists(pdf)) {
        workDir_->keep();
        throw ProcessingError(
            std::format("pdftex failed (exit status {}); see {}", status, (dir / "document.log").string()));
    }
    std::filesystem::copy_file(pdf, output_, std::filesystem::copy_options::overwrite_existing);
    workDir_.reset();
}

std::string PdfExporter::texDocument() const
{
    std::string tex = std::format(kPreamble, kVersion);
    for (const auto& page : pages_) {
        const Placement p = paper_.place(page.size);
        tex += std::format("\\page{{{:.3f}}}{{{:.3f}}}{{{:.3f}}}{{{:.3f}}}{{{:.3f}}}{{{:.3f}}}{{{}}}\n", p.pageWidth,
                           p.pageHeight, p.x, p.y, p.width, p.height, page.name.string());
    }
    return tex + "\\end\n";
}

} // namespace docscan
